'Challenging-Macro-Environment':
  'description': '<p><!--StartFragment -->The JCI rebounded to about 7,000 after bottoming
    out at 5,968 on 9 April, following a series of developments including...</p>

    '
  'image': 'jcr:ac2509d4-51b7-46c7-8e24-13e7c3a301e0'
  'jcr:primaryType': 'mt:featureC2'
  'jcr:uuid': '524da5ed-b229-44e9-985a-d4be142bf3cd'
  'mgnl:created': 2025-12-23T13:43:43.068+08:00
  'mgnl:createdBy': 'superuser'
  'mgnl:lastModified': 2025-12-23T13:47:11.538+08:00
  'mgnl:lastModifiedBy': 'superuser'
  'name': 'Challenging Macro Environment'
  'tag': 'Major markets'
  'title': 'Challenging Macro Environment, More Reason For A Rate Cut'
  'ctaChooser':
    'detailPage': 'bccac67c-e599-4a78-8ee5-e9029a5248fd'
    'isExternal': false
    'jcr:uuid': 'eb8d4186-dae1-4302-896d-964071173bb5'
    'label': 'Read more'
    'mgnl:created': 2025-12-23T13:43:43.103+08:00
    'mgnl:createdBy': 'superuser'
    'mgnl:lastModified': 2025-12-23T13:43:43.103+08:00
    'mgnl:lastModifiedBy': 'superuser'
