'Challenging-Macro-Environment':
  'description': '<p><!--StartFragment -->The JCI rebounded to about 7,000 after bottoming
    out at 5,968 on 9 April, following a series of developments including...</p>

    '
  'image': 'jcr:ac2509d4-51b7-46c7-8e24-13e7c3a301e0'
  'jcr:mixinTypes': ['mgnl:hasVersion']
  'jcr:primaryType': 'mt:featureC2'
  'jcr:uuid': '524da5ed-b229-44e9-985a-d4be142bf3cd'
  'mgnl:activationStatus': true
  'mgnl:created': 2025-12-23T13:43:43.068+08:00
  'mgnl:createdBy': 'superuser'
  'mgnl:lastActivated': 2026-01-06T12:11:44.998+08:00
  'mgnl:lastActivatedBy': 'superuser'
  'mgnl:lastActivatedVersion': '1.2'
  'mgnl:lastActivatedVersionCreated': 2026-01-06T12:11:44.687+08:00
  'mgnl:lastModified': 2026-01-06T12:11:40.995+08:00
  'mgnl:lastModifiedBy': 'superuser'
  'name': 'Challenging Macro Environment'
  'tag': 'Major markets'
  'title': 'Challenging Macro Environment, More Reason For A Rate Cut'
  'ctaChooser':
    'detailPage': '6f1747e7-fac8-4fe1-b8e2-0c1545e37ff0'
    'isExternal': false
    'jcr:uuid': 'eb8d4186-dae1-4302-896d-964071173bb5'
    'label': 'Read more'
    'mgnl:activationStatus': true
    'mgnl:created': 2025-12-23T13:43:43.103+08:00
    'mgnl:createdBy': 'superuser'
    'mgnl:lastActivated': 2026-01-06T12:11:44.998+08:00
    'mgnl:lastActivatedBy': 'superuser'
    'mgnl:lastModified': 2026-01-06T12:11:40.995+08:00
    'mgnl:lastModifiedBy': 'superuser'
